[package]
name = "tum-module-picker"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["debug"]}
iced_aw = {version = "0.12.2"}
iced_fonts = {version = "0.2.1", features = ["nerd"]}

time = {version = "0.3.44"}

regex = {version = "1.11.3"}
